AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 básica en Ohio (us-east-2)

Parameters:
  KeyName:
    Description: Nombre del KeyPair para SSH
    Type: AWS::EC2::KeyPair::KeyName

  InstanceType:
    Description: Tipo de instancia
    Type: String
    Default: t3.micro

  ImageId:
    Description: AMI ID
    Type: String

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !Ref ImageId
      Tags:
        - Key: Name
          Value: MiEC2Basica